jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install pillow requests beautifulsoup4

    - name: Delete old images folder, commit and push
      run: |
        rm -rf images/
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git rm -rf images/ || true
        git commit -m "Remove old images folder" || echo "Nothing to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

    - name: Run generate_rolls.py
      run: python generate_rolls.py

    - name: Commit and push generated image folders
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add images/roll*
        git commit -m "Auto-generate roll images on push" || echo "Nothing to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
      continue-on-error: true

    - name: Upload generated images as artifact
      uses: actions/upload-artifact@v4
      with:
        name: roll-images
        path: images/roll*/

    - name: Deploy to GitHub Pages (if needed)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
